name: Deploy on CentOS
runs:
  using: composite
  steps:
    - name: Install environment
      shell: bash
      run: |
        echo "current working dir is `pwd`"
        cd /root

        SCL_ENABLE="devtoolset-9"
        CENTOS_VERSION=$(rpm --eval '%{centos_ver}')
        if [[ "$CENTOS_VERSION" == "6" ]]; then
          find /etc/yum.repos.d/ -name *.repo | xargs -i sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/$releasever/6.10/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' {}
          SCL_ENABLE="devtoolset-9 rh-python36 python27"
        fi
        echo "SCL_ENABLE=$SCL_ENABLE" >> $GITHUB_ENV

        yum -y update
        yum -y install centos-release-scl-rh epel-release
        if [[ "$CENTOS_VERSION" == "6" ]]; then
          sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/6\/sclo/6.10\/sclo/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
        fi
        yum -y install $SCL_ENABLE rh-java-common-ant boost-devel ccache clang gcc-c++ gcc-gfortran java-1.8.0-openjdk-devel ant python python36-devel python36-pip swig file which wget unzip tar bzip2 gzip xz patch autoconf-archive automake make libtool bison flex perl nasm alsa-lib-devel freeglut-devel gtk2-devel libusb-devel libusb1-devel curl-devel expat-devel gettext-devel openssl-devel bzip2-devel zlib-devel SDL-devel libva-devel libxkbcommon-devel libxkbcommon-x11-devel xcb-util* fontconfig-devel libffi-devel ragel ocl-icd-devel GeoIP-devel pcre-devel ssdeep-devel yajl-devel
        # https://gcc.gnu.org/legacy-ml/gcc-patches/2018-01/msg01962.html
        sed -i 's/_mm512_abs_pd (__m512 __A)/_mm512_abs_pd (__m512d __A)/g' /opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/include/avx512fintrin.h
        source scl_source enable $SCL_ENABLE || true

        curl -LO https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6-Linux-x86_64.tar.gz
        curl -LO https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        curl -LO https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.18.3.tar.gz
        curl -LO https://services.gradle.org/distributions/gradle-6.7.1-bin.zip
        tar -xzf cmake-3.16.6-Linux-x86_64.tar.gz -C /opt/
        tar -xzf apache-maven-3.6.3-bin.tar.gz -C /opt/
        tar -xzf git-2.18.3.tar.gz
        unzip gradle-6.7.1-bin.zip -d /opt/
        pushd git-2.18.3; make -j2 prefix=/usr/local/; make -j2 prefix=/usr/local/ install; popd
        ln -sf /usr/bin/python3.6 /usr/bin/python3
        ln -sf /opt/cmake-3.16.6-Linux-x86_64/bin/* /usr/bin/
        ln -sf /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        ln -sf /opt/gradle-6.7.1/bin/gradle /usr/bin/gradle

        if [[ -n ${CI_DEPLOY_NEED_GCC:-} ]]; then
          rm -f /usr/lib/libgfortran.so.3* /usr/lib64/libgfortran.so.3* # not required for GCC 7+
        else
          rm -f /usr/lib/libgfortran.so.4* /usr/lib64/libgfortran.so.4* # remove library from GCC 7+
        fi


    - name: Build project
      shell: bash
      run: |
        echo "current working dir is `pwd`"
        source scl_source enable $SCL_ENABLE || true
        git --version
        gcc --version
        cmake --version
        gradle --version
        mvn -version
        gpg --version
        python3 --version
        df -h

        export MAKEJ=$(getconf _NPROCESSORS_ONLN)
        echo Fetching $GITHUB_REPOSITORY@$GITHUB_SHA
        git init
        git fetch --depth 1 https://github.com/$GITHUB_REPOSITORY $GITHUB_SHA
        git checkout $GITHUB_SHA
        git submodule update --init --recursive
        git submodule foreach --recursive 'git reset --hard'

        echo "Fixing HOME to /root (was '$HOME')"
        export HOME=/root


        SECONDS=$(( RANDOM % 300 ))
        echo Sleeping $SECONDS seconds to help avoid race conditions with Maven
        sleep $SECONDS

        echo "current working dir is `pwd`"
        df -h
        mvn clean package -Djavacpp.platform=linux-x86_64
        

#    - name: upload jar
#      uses: actions/upload-artifact@v3
#      with:
#        name: cpython-platform-3.10.2-1.5.7.jar
#        path: /root/.m2/repository/org/bytedeco/cpython-platform/3.10.2-1.5.7/cpython-platform-3.10.2-1.5.7.jar

    - name: Clean up
      shell: bash
      run: |
        cd /root
        rm -Rf $(find .m2/repository/ -name '*SNAPSHOT*')